name: homeassistant-freyes
base: core18 # the base snap is the execution environment for this snap
version: '0.103.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Open-source home automation platform
description: |
  Home Assistant is able to track and control all devices at home and offer a
  platform for automating control.

  Featured integrations

  The system is built using a modular approach so support for other devices or
  actions can be implemented easily. See also the `section on architecture
  <https://developers.home-assistant.io/docs/en/architecture_index.html>`__ and
  the `section on creating your own components
  <https://developers.home-assistant.io/docs/en/creating_component_index.html>`__.

  If you run into issues while using Home Assistant or during development of a
  component, check the `Home Assistant help section
  <https://home-assistant.io/help/>`__ of our website for further help and
  information.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  hass:
    command: hass
    daemon: simple

parts:
  homeassistant:
    plugin: python
    source: https://github.com/home-assistant/home-assistant.git
    source-tag: "0.103.0"
    build-packages:
      - python3-dev
      - libffi-dev
      - libssl-dev
