name: home-assistant-freyes
base: core20 # the base snap is the execution environment for this snap
version: '0.112.3'
summary: Open-source home automation platform
description: |
  Home Assistant is able to track and control all devices at home and offer a
  platform for automating control.

  Featured integrations

  The system is built using a modular approach so support for other devices or
  actions can be implemented easily. See also the `section on architecture
  <https://developers.home-assistant.io/docs/en/architecture_index.html>`__ and
  the `section on creating your own components
  <https://developers.home-assistant.io/docs/en/creating_component_index.html>`__.

  If you run into issues while using Home Assistant or during development of a
  component, check the `Home Assistant help section
  <https://home-assistant.io/help/>`__ of our website for further help and
  information.

adopt-info: core
confinement: strict

apps:
  hass:
    command: bin/hass
    daemon: simple
    plugs:
      - network
      - network-bind

parts:
  core:
    plugin: python
    source: https://github.com/home-assistant/core.git
    source-tag: ${SNAPCRAFT_PROJECT_VERSION}
    build-packages:
      - python3-dev
      - python3-pip
      - python3-venv
      - python3-wheel
      - libffi-dev
      - libssl-dev
      - build-essential
      - autoconf
      - python-pyrex
      - pkg-config
      - libudev-dev
      - libopenzwave1.5-dev
      - libglib2.0-dev
      - libavformat-dev
      - libavcodec-dev
      - libavdevice-dev
      - libavutil-dev
      - libavfilter-dev
      - libswscale-dev
      - libswresample-dev
      - cython3
      # lxml python binary package not available, this is needed to compile it from sources
      - libxml2-dev
      - libxslt1-dev
      - cmake  # needed to compile uamqp
      # needed to compile Pillow
      - libjpeg-dev
      - libfreetype6-dev
      - zlib1g-dev
      - liblcms2-dev
      - libtiff5-dev
      - libwebp-dev
      - libraqm-dev
      - libimagequant-dev
    override-pull: |
      snapcraftctl pull
        version="$(git describe --tags --always --dirty)"
        [ -n "$(echo $version | grep '-')" ] && grade=devel || grade=stable
        snapcraftctl set-version "$version"
        snapcraftctl set-grade "$grade"
    override-build: |
      python3 -m venv $SNAPCRAFT_PART_INSTALL
      $SNAPCRAFT_PART_INSTALL/bin/python3 -m pip install wheel
      snapcraftctl build
    requirements:
      - $SNAPCRAFT_PROJECT_DIR/snap/local/local_requirements.txt
      - requirements_all.txt
    constraints:
      - homeassistant/package_constraints.txt
      - $SNAPCRAFT_PROJECT_DIR/snap/local/local_constraints.txt
